# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flink_processor/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flink_processor/messages.proto',
  package='demo',
  syntax='proto3',
  serialized_pb=_b('\n\x1e\x66link_processor/messages.proto\x12\x04\x64\x65mo\"1\n\x0fTransferRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\";\n\x10TransferResponse\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x63knowledgement\x18\x02 \x01(\t\"\"\n\x10\x41mountTransfered\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x62\x06proto3')
)




_TRANSFERREQUEST = _descriptor.Descriptor(
  name='TransferRequest',
  full_name='demo.TransferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='demo.TransferRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='demo.TransferRequest.amount', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=89,
)


_TRANSFERRESPONSE = _descriptor.Descriptor(
  name='TransferResponse',
  full_name='demo.TransferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='demo.TransferResponse.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acknowledgement', full_name='demo.TransferResponse.acknowledgement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=150,
)


_AMOUNTTRANSFERED = _descriptor.Descriptor(
  name='AmountTransfered',
  full_name='demo.AmountTransfered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='demo.AmountTransfered.amount', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['TransferRequest'] = _TRANSFERREQUEST
DESCRIPTOR.message_types_by_name['TransferResponse'] = _TRANSFERRESPONSE
DESCRIPTOR.message_types_by_name['AmountTransfered'] = _AMOUNTTRANSFERED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransferRequest = _reflection.GeneratedProtocolMessageType('TransferRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERREQUEST,
  __module__ = 'flink_processor.messages_pb2'
  # @@protoc_insertion_point(class_scope:demo.TransferRequest)
  ))
_sym_db.RegisterMessage(TransferRequest)

TransferResponse = _reflection.GeneratedProtocolMessageType('TransferResponse', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERRESPONSE,
  __module__ = 'flink_processor.messages_pb2'
  # @@protoc_insertion_point(class_scope:demo.TransferResponse)
  ))
_sym_db.RegisterMessage(TransferResponse)

AmountTransfered = _reflection.GeneratedProtocolMessageType('AmountTransfered', (_message.Message,), dict(
  DESCRIPTOR = _AMOUNTTRANSFERED,
  __module__ = 'flink_processor.messages_pb2'
  # @@protoc_insertion_point(class_scope:demo.AmountTransfered)
  ))
_sym_db.RegisterMessage(AmountTransfered)


# @@protoc_insertion_point(module_scope)
